-- Managed by the Omarchy Hot Corners plugin (io.github.sahzudin.hotcorners).
-- Do not edit this file by hand; use the Hot Corners settings panel.
--
-- Template for ~/.config/hypr/hotcorners/init.lua. The two placeholder
-- strings below are filled in at install time by scripts/hotcorners.py.

-- Tear down the previous instance on config reload so repeated `hyprctl reload`
-- does not leave orphaned polling timers behind.
if _G.omarchy_hotcorners then
  pcall(_G.omarchy_hotcorners.stop)
end

_G.omarchy_hotcorners_memory = _G.omarchy_hotcorners_memory or {}

local PLUGIN_MANIFEST = "@@PLUGIN_MANIFEST@@"
local CLEANUP_COMMAND = "@@CLEANUP_COMMAND@@"

local function readable(path)
  local handle = io.open(path, "r")
  if handle then
    handle:close()
    return true
  end
  return false
end

-- `omarchy plugin remove` deletes the checkout without running any plugin
-- code, so this is where a removed plugin notices it is gone and tidies up:
-- the hook, the menu entry, the shell registration, and this directory. Until
-- then it stays inert rather than binding corners to a plugin that is no
-- longer installed.
if not readable(PLUGIN_MANIFEST) then
  _G.omarchy_hotcorners = nil
  pcall(hl.exec_cmd, CLEANUP_COMMAND)
  return
end

local ok, cfg = pcall(require, "hypr.hotcorners.config")
if not ok or type(cfg) ~= "table" then
  cfg = {
    corners = {
      ["top-left"] = "apps-menu",
      ["top-right"] = "launcher",
      ["bottom-left"] = "show-desktop",
      ["bottom-right"] = "next-workspace",
    },
    custom = {},
    options = { dwell = 250, corner = 10, edge = 4 },
  }
end

local options = cfg.options or {}

local mousetrap = require("hypr.hotcorners.mousetrap.init").setup({
  motion = { timer = 16 },
  geometry = {
    default = {
      corner = options.corner or 10,
      edge = options.edge or 4,
    },
  },
})

-- Show desktop: stash every window on the active workspace into a special
-- workspace, and restore them on the next trigger. Origin workspaces are
-- remembered so windows return where they came from.
local function show_desktop()
  local monitor = hl.get_active_monitor()
  if not monitor then
    return
  end

  local desktop = hl.get_workspace("special:desktop")

  if desktop then
    for _, window in pairs(hl.get_windows({ workspace = desktop })) do
      local origin = _G.omarchy_hotcorners_memory[tostring(window.address)] or monitor.active_workspace.id
      hl.dispatch(hl.dsp.window.move({ window = window, workspace = tostring(origin), follow = false }))
    end

    _G.omarchy_hotcorners_memory = {}
  else
    local origin = monitor.active_workspace.id

    for _, window in pairs(hl.get_windows({ workspace = monitor.active_workspace })) do
      _G.omarchy_hotcorners_memory[tostring(window.address)] = origin
      hl.dispatch(hl.dsp.window.move({ window = window, workspace = "special:desktop", follow = false }))
    end
  end
end

-- Action registry: id -> callback factory. The "custom" factory takes the
-- shell command configured for its corner.
local action = {
  ["none"] = function()
    return nil
  end,
  ["apps-menu"] = function()
    return function()
      hl.exec_cmd("omarchy-menu toggle apps")
    end
  end,
  ["launcher"] = function()
    return function()
      hl.exec_cmd("omarchy-menu toggle")
    end
  end,
  ["show-desktop"] = function()
    return show_desktop
  end,
  ["next-workspace"] = function()
    return function()
      hl.dispatch(hl.dsp.focus({ workspace = "e+1" }))
    end
  end,
  ["prev-workspace"] = function()
    return function()
      hl.dispatch(hl.dsp.focus({ workspace = "e-1" }))
    end
  end,
  ["fullscreen"] = function()
    return function()
      hl.dispatch(hl.dsp.window.fullscreen({ mode = "fullscreen" }))
    end
  end,
  ["close-window"] = function()
    return function()
      hl.dispatch(hl.dsp.window.close())
    end
  end,
  ["custom"] = function(command)
    return function()
      if command and command ~= "" then
        hl.exec_cmd(command)
      end
    end
  end,
}

local corners = { "top-left", "top-right", "bottom-left", "bottom-right" }
local any_enabled = false

for _, corner in ipairs(corners) do
  local id = cfg.corners and cfg.corners[corner]

  if id and id ~= "none" then
    local builder = action[id]

    if builder then
      local command = (id == "custom") and (cfg.custom and cfg.custom[corner]) or nil
      local callback = builder(command)

      if callback then
        mousetrap.bind(corner, callback, { delay = options.dwell or 250 })
        any_enabled = true
      end
    end
  end
end

if any_enabled then
  mousetrap.start()
end

-- Expose the module and actions so they can be invoked from `hyprctl eval`
-- (handy for debugging and re-running an action by hand).
_G.omarchy_hotcorners = mousetrap
_G.omarchy_hotcorners.actions = {
  show_desktop = show_desktop,
}
